### ISSUE TITLE
[Version 0.16.0] ユーザー認証周りのセキュリティを改善する

### ISSUE THREAD

**Issue by junt1458** [nit-gifu-gis/boar-map#112]
CookieにユーザーIDやトークンを保存しているのですが、拡張機能などでCookieを書き換えると、別の権限のユーザーとして認識されてしまう可能性があります。

![image](https://user-images.githubusercontent.com/40569974/88127917-ca5eaf00-cc0f-11ea-96a7-28a267f11468.png)

（できるなら）外部サーバーとかを使って、ＪＷＴとかを使って発行/検証を行うような処理を追加したほうがいいかもしれません。

（サーバー側でRead/Writeの権限が適切に設定されている場合は大丈夫かもしれません。）

**Comment by lalaso2000** [comment]
Read/Write周りの権限、一度確認しておくね
だいぶ前にあったissueで間違ってたのがあるから

**Comment by lalaso2000** [comment]
これが間違ってなければ、対策は一応不要…かな？
アクセストークンが発行できなければ少なくともwriteされることはなさそう

**Comment by junt1458** [comment]
R/Wの権限がちゃんとしてれば大丈夫だと思います！

**Comment by lalaso2000** [comment]
@junki-gnct 
確認したら，Rのみの権限が与えられてる部分にDB側のバグがあるっぽい
(Rのみのはずのワクチン業者のわな登録が通る，ワクチン業者の捕獲情報はサーバーエラー)

とりあえずDBの開発元に今問い合わせてるけど，どうする？

**Comment by lalaso2000** [comment]
この件に関してはAPIをラップするときに対策できそう
10月以降に回します

**Comment by lalaso2000** [comment]
中間サーバーが完成したらそのAPIに差し替え（https://gis-dev.junki-t.net/v1）
- [x] ログイン（/Authorization/GetToken）
- [x] ログアウト（/Authorization/DeleteToken）
- [x] 空間検索（/Feature/GetFeaturesByExtent）
- [x] フィーチャ取得（/Feature/GetFeaturesById）
- [x] フィーチャ追加（/Feature/AddFeatures）
- [x] フィーチャ編集（/Feature/UpdateFeatures）
- [x] フィーチャ削除（/Feature/DeleteFeatures）
