### ISSUE TITLE
pc版 firefoxからログインできない

### ISSUE THREAD

**Issue by lalaso2000** [nit-gifu-gis/boar-map#18]
## 発生状況
- Windows / MacOSのFireFoxでログインできない
- CORS要求が通らないらしい
- iOS版FireFoxは大丈夫

**Comment by lalaso2000** [comment]
サーバー側の原因な気がしてきた
`Access-Control-Allow-Credentials`が返ってきてなくてクライアントサイドでエラーしてるかも
[参考](https://devpixiv.hatenablog.com/entry/2014/12/16/181804)

**Comment by junt1458** [comment]
CORSはAPIサーバー側のヘッダーに追加してもらう必要があったはずですね

**Comment by lalaso2000** [comment]
明日辺り問い合わせてみます

**Comment by lalaso2000** [comment]
ちなみにAndroid版FireFoxなど、他にもログイン出来ないブラウザがあるっぽい

**Comment by junt1458** [comment]
iOSのChromeとかFirefoxは中身結局Safariってのを見たことがある気がするので、そこでFirefoxの動作が分かれてるのかもしれません

**Comment by lalaso2000** [comment]
結局これはサーバー側の問題で解決の見込みなしとのことなので放置でお願いします

**Comment by junt1458** [comment]
bug/#18-2 で、ログイン/ログアウト/情報の取得/地図の表示まで実装。
情報の操作は、サーバー側のエラーにより未実装
（アクセストークンが設定されていないエラー）
![image](https://user-images.githubusercontent.com/40569974/70809814-ee4e4c80-1e05-11ea-9b6a-7a89834104b0.png)
送信しているはずのheaderにはtokenの記述あり

**Comment by junt1458** [comment]
#33 に統合
