### ISSUE TITLE
Windows版Microsoft Edgeで情報登録ができない

### ISSUE THREAD

**Issue by lalaso2000** [nit-gifu-gis/boar-map#33]
~- 要求本文も応答も文字化けするため送信できない~
~- #22 と同時に直します~

**Comment by lalaso2000** [comment]
文字コードが原因では無いらしい
アクセストークンが何故かセットされないらしい・・・？

**Comment by lalaso2000** [comment]
上の画像（要求ヘッダー）ではちゃんとアクセストークンがセットされているのにも関わらず，下の画像のエラーが出る．
![image](https://user-images.githubusercontent.com/20383042/70408929-4810e880-1a8d-11ea-86ee-29ca97a567ea.png)
![image (1)](https://user-images.githubusercontent.com/20383042/70408928-4810e880-1a8d-11ea-84d8-018ff6759c15.png)

**Comment by lalaso2000** [comment]
問題がややこしそうなので #22 だけ先に直します

**Comment by junt1458** [comment]
#18 の対策用スクリプトにも同様の問題が発生したため一部保留中。
この問題が解決次第、そちらも対応する。
