### ISSUE TITLE
直接アクセスしたときの例外処理

### ISSUE THREAD

**Issue by junt1458** [nit-gifu-gis/boar-map#35]
https://boar-map-git-feature-20.nit-gifu-gis.now.sh/add/location
に直接アクセスすることができるので、直アクセスはマップなどに移動するようにする。

※この状態で次へを押すと、/add/info/undefined になるため404が発生する。

**Comment by lalaso2000** [comment]
add/info/XXのページとadd/confrim/XXのページもadd/locationと同様に処理しようとしたら、「Error: No router instance found. You should only use "next/router" inside the client side of your app.」になる．
（これらのページで再読み込みした場合も同様）

なにか別の対策が必要っぽい
