### ISSUE TITLE
情報の書き込み権限のチェック

### ISSUE THREAD

**Issue by junt1458** [nit-gifu-gis/boar-map#36]
コード的には、書き込み権限がない人も入力フォームを表示することができる気がします
（通常の画面上からはいけません）

API側で書き込み権限の制御がされている場合は対応はどちらでも大丈夫です。

**Comment by lalaso2000** [comment]
~API側で書き込み権限の制御をかけたはずですが，何故か通り抜けたので対応します~
DB側のミスのようです
（ワクチン業者が本来書き込めない「捕獲いのしし」と「わな」を登録できる）
それ以外の人は書き込もうとするとエラーになるので，この件は一旦後回しにします

**Comment by lalaso2000** [comment]
DB側のミスが3月末にならないと直らないらしいのでやっぱり対応の必要があります

**Comment by lalaso2000** [comment]
#62 で該当ページの修正が行われるまで保留
feature/#62からブランチ派生させる方針で

…3月末が来てしまいそうですが、念の為対処する方針で

**Comment by lalaso2000** [comment]
4月も末が近づいていますが，DB側多分修正予定ないので対応します

**Comment by lalaso2000** [comment]
#74 が落ち着いたので実装開始します

**Comment by lalaso2000** [comment]
- [x] ワクチン情報をW,Kに制限
- [x] いのしし登録をT,U,S,Kに制限
- [x] 罠登録をT,U,S,Kに制限
- [x] ワクチン登録をW,Kに制限
