### ISSUE TITLE
iOSで情報取得に失敗する

### ISSUE THREAD

**Issue by lalaso2000** [nit-gifu-gis/boar-map#43]
相変わらずのfetchバグ
マップより詳細情報の方が失敗確率高い気がする？

**Comment by lalaso2000** [comment]
@junki-gnct [これの可能性が微レ存…？](https://qiita.com/IYA_UFO/items/f01eb2de45eddac0f127)
fetchを呼ぶのはgetInititalPropsじゃないとダメ説

**Comment by junt1458** [comment]
詳細取得の方はgetInitialPropsでもいいんですが、ピン取得の方は、そうはいかないんですよね...
ページが読み込まれた時しか呼ばれないので、マップ移動時ってのが無理そう

**Comment by lalaso2000** [comment]
@junki-gnct  ピン表示の方、リトライ投入してから失敗してるところ見てないんだけど、見た？
ssr無効化してるから大丈夫説ある…？
詳細取得の方はちょっと1回やってみる価値あるかもと思ってる

**Comment by junt1458** [comment]
ピン表示のほうは失敗したところ見たことないですね

**Comment by junt1458** [comment]
詳細取得のほうはやってみる価値はあると思います

**Comment by lalaso2000** [comment]
@junki-gnct お願いしてもいい?

**Comment by junt1458** [comment]
OKです

**Comment by junt1458** [comment]
コードにミスがあって詳細画面でそもそもリトライしてなかった説があるので修正してみました

一旦これで確認をお願いしたいです 🙏

**Comment by lalaso2000** [comment]
@junki-gnct ぱっと15回くらいやってみたけど1回も失敗しなかった
とりあえずこれでいってみようかな

**Comment by lalaso2000** [comment]
ピンの方、一旦ピンが1本もないところを表示した後にもう一度ピンがある場所を表示しようとするとほぼ100%失敗するな…

**Comment by lalaso2000** [comment]
あ，↑のは単純に無限ループに入ってる別のバグだ
issue立てます
