### ISSUE TITLE
ピン取得時に無限ループする

### ISSUE THREAD

**Issue by lalaso2000** [nit-gifu-gis/boar-map#44]
一度ピンが一本もない場所を表示したあとにもう一度ピンがある場所を表示しようとすると無限ループする

**Comment by lalaso2000** [comment]
#43 から分離

**Comment by lalaso2000** [comment]
tyousa / yuugai / shityousonのようにワクチンの表示権限がない人もワクチンを表示しようとして無限ループしてるっぽい

**Comment by junt1458** [comment]
#43 のブランチをベースに作業します
