### ISSUE TITLE
処理中であることが分かるようにしたい

### ISSUE THREAD

**Issue by lalaso2000** [nit-gifu-gis/boar-map#75]
### 概要
GISサーバで処理を行う場面で，処理中であることが画面に現れないため，ボタンを連打される危険がある．

### 具体的な発生場所

- [x] ログイン処理（/login）
- [ ] ~ログアウト処理（メニューバーのログアウト）~
- [x] 登録処理（/add/confirm）
- [x] 変更処理（/edit/confirm）
- [x] 画像アップロード（/add/info）
- [x] 画像アップロード（/edit/info）

**Comment by lalaso2000** [comment]
処理中はボタンが押せないようにしておくことが多分有効
グルグルも出してもいいかも？

**Comment by junt1458** [comment]
高確率で #74 とConflictすると思うので、それ終わってからでお願いしたいです 🙏 

ボタンを無効にしてグルグル出すのがいいかと

**Comment by lalaso2000** [comment]
ok

次 #36 辺りやろうかなって思ってたけど、他も一旦止めた方がいいかな？

**Comment by junt1458** [comment]
ですね、結構大きく変更してるので...
一応あとGISにIDを登録したりGISから移動を取得する処理を書けば終わるのでもう少しだけ待っていただけると！
(登録するField名がわからない状態)

**Comment by lalaso2000** [comment]
ok
…画像登録用のフィールド無いわ
ちょっと急ぎで作ってもらうね

**Comment by lalaso2000** [comment]
idの形式教えて貰っていい？

**Comment by junt1458** [comment]
idは、半角英数字(A-Z,a-z,0-9)の16文字（長さは固定、プログラムをいじれば変更可）です。
画像1枚に対して1つのIDが発行されるので、一つのスポットに対して複数枚の登録があるときは、フィールドにカンマ区切りとかで保存することを想定してます。

1枚の時→p9YgsbDwI6MIxA5I
2枚の時→p9YgsbDwI6MIxA5I,pAPEkMR1SB7dTRrB
3枚の時→p9YgsbDwI6MIxA5I,pAPEkMR1SB7dTRrB,pBCTlxf6M8NTVdHJ

みたいな感じです

**Comment by lalaso2000** [comment]
ok
フィールド自体を配列にすることもできるけど…って思ったけど、可変長配列かどうか怪しいし、とりあえずそれで行こか
文字列の字数制限があるかもしれないからそのへんも聞いておくね
(前作ってもらったフィールドは半角50文字だった(短い))

**Comment by junt1458** [comment]
可変長配列でいけるなら配列でも大丈夫です！

(APIリファレンスには任意のフィールド名、string(250)とかあったし250文字くらいは大丈夫そう？)

**Comment by lalaso2000** [comment]
そのへんも含めて明日とりあえずメールしてみるね

**Comment by lalaso2000** [comment]
画像アップロードで少し重くなったので急ぎで対処します
