### ISSUE TITLE
Vercelでのデプロイ時に画像サーバーにログインできない問題

### ISSUE THREAD

**Issue by junt1458** [nit-gifu-gis/boar-map#99]
画像サーバーから帰ってくるJWTが正常にCookieにセットされていないことによる問題だと推測します。

**Comment by lalaso2000** [comment]
これ単純に不具合なので，解消し次第masterにマージしてバージョン更新する方針でお願い

[meta]
[version]Version 0.11.1[/version]
[contents]
一部の端末・ブラウザから画像が登録できない不具合を解消しました
[/contents]
[/meta]

**Comment by junt1458** [comment]
サーバー側でCookieをセットするときに、別ドメインの場合はSecureオプションをつけないと行けなかったみたいなのでつけてサーバー側のリポジトリにプッシュしました。

こちらでは、ログイン時に送るセッション有効期限の式が間違っていたのでついでに修正しました。

表示/アップロードの確認済みです
![D84782AD-0F08-407B-AEEA-43D96BC1ED95](https://user-images.githubusercontent.com/40569974/84670703-6afee680-af61-11ea-9bf4-ca7834ee14c4.png)
